### ISSUE TITLE
should we support non-zip node action with exports.main?

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-runtime-nodejs#14]
@rabbah commented on [Tue Oct 31 2017](https://github.com/apache/incubator-openwhisk/issues/2918)

if you declare a node.js action with a `function foo` and use `exports.main = foo`, the action will fail to run `Initialization has failed due to: ReferenceError: main is not defined`. Currently we're only supporting `exports.main` for zip node.js action. Should we allow it for non-zip actions as well?

The alternative is using `--main` for the CLI or correspondingly from the API.
This could be an issue for the nodejs runtimes library - @csantanapr wdyt?

---

@jthomas commented on [Thu Nov 09 2017](https://github.com/apache/incubator-openwhisk/issues/2918#issuecomment-343185255)

I would definitely like this. Would be a nice feature for consistency.

**Comment by csantanapr** [comment]
Yeah I think it should be ok to allow export

In addition there should be a test to make sure using a bundler like webpack is added to detect any regressions in the future

**Comment by moritzraho** [comment]
One workaround that worked for me (I packaged my action using parcel) is to set `--main module.exports.main` when creating the action
