### ISSUE TITLE
Gradle : Incompatible versions

### ISSUE THREAD

**Issue by Rurouni-Jiaxin** [apache/openwhisk-runtime-nodejs#229]
## Environment details:

* local deployment  
* version of docker: 20.10.17, gradle: 6.9.1.

## Steps to reproduce the issue:

1.   Run the `distDocker` command to generate the local Docker image for the desired runtime version. 

## Provide the expected results and outputs:

```
Create the runtime image 
```

## Provide the actual results and outputs:

```
Build successful, though with warning "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."
```

**Comment by Rurouni-Jiaxin** [comment]
@upgl. Would you please be so kind and give me a hint? Because I see you previously bumped the gradle version

**Comment by rabbah** [comment]
> Build successful, though with warning "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."

this looks like a warning rather than a build failure. Did the docker image not get built?
