### ISSUE TITLE
support typescript as source

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk-runtime-nodejs#42]
have the ability to take a source in typescript format.
This is useful for development time, but as always is recommended to compile into a bundle js, no transpile require on `/init` for production workloads.

**Comment by rabbah** [comment]
This might a good candidate for action loop (with its compiler) - cc @mscibarra.

**Comment by sciabarracom** [comment]
Yup but the nodejs does not use actionloop as a proxy - we may add a -compile flag as in the actionloop based runtimes ...

**Comment by rabbah** [comment]
You can create a new typescript action that is action loop based?

**Comment by sciabarracom** [comment]
I can. 

-- 
 Michele Sciabarra
 michele@sciabarra.com



----- Original message -----

**Comment by sciabarra** [comment]
I did :D
