### ISSUE TITLE
Could we add `node-cache` to the list of default packages?

### ISSUE THREAD

**Issue by ScottChapman** [apache/openwhisk-runtime-nodejs#76]
[`node-cache`](https://www.npmjs.com/package/node-cache) is a very popular simple/fast internal caching package. Right now I don't think there are any reasonable caching options for actions. I think this would be a really useful addition, especially for actions that can stay warm...

**Comment by rabbah** [comment]
We can - but the project has generally taken the approach of not bundling much into the base image as providers tend to offer their own images.
